{% set name = "mssql-scripter" %}
{% set version = "1.0.0a23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/mssql-scripter/archive/v{{ version }}.tar.gz
  sha256: 863b820f4ddd0715d01ae7c38047b9396d35fb705222bbaeae5f59e708c0cfa0

build:
  number: 6
  merge_build_host: true  # workaround conda-build bug on windows

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future >=0.16.0
    - openssl =1.0

test:
  imports:
    - mssqlscripter
  requires:
    - pip
  commands:
    - mssql-scripter --version
    - pip check

about:
  home: https://github.com/microsoft/mssql-scripter
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Microsoft SQL Scripter Command-Line Tool'
  description: |
    mssql-scripter is the multiplatform command line equivalent of the widely
    used Generate Scripts Wizard experience in SSMS. You can use mssql-scripter
    on Linux, macOS, and Windows to generate data definition language (DDL) and
    data manipulation language (DML) T-SQL scripts for database objects in SQL
    Server running anywhere, Azure SQL Database, and Azure SQL Data Warehouse.
    You can save the generated T-SQL script to a .sql file or pipe it to
    standard nix utilities (for example, sed, awk, grep) for further
    transformations. You can edit the generated script or check it into source
    control and subsequently execute the script in your existing SQL database
    deployment processes and DevOps pipelines with standard multiplatform SQL
    command line tools such as sqlcmd.
  dev_url: https://github.com/microsoft/mssql-scripter

extra:
  recipe-maintainers:
    - borchero
    - svengiegerich
    - maresb
